menu:
  - name: Home
    url: /
  - name: Categories
    url: /categories/
  - name: Tags
    url: /tags/
  - name: Archives
    url: /archives/
  - name: Friends
    url: /friends/

socialLink:
  - name: Github
    link: https://github.com/hai-zou/

friends:
  - name: 旧梦
    avatar: //imgs.izou.top/user/avatar.jpg
    link: //blog.izou.top
    desc: 冰冻三尺非一日之寒，滴水穿石非一日之功

footer:
  builtUpTime: 2024-05-28

comment:
  enable: false
  type: giscus

giscus:
  repo: hai-zou/hexo-theme-sea
  repoid: R_kgDOLD6S2g
  category: General
  categoryid: DIC_kwDOLD6S2s4CgP0r
  mapping: pathname
  strict: "0"
  reactionsenabled: "1"
  emitmetadata: "0"
  inputposition: bottom
  loading: lazy

search:
  enable: true # 是否启用
  type: algolia

# Docsearch https://docsearch.algolia.com/apply/
algolia:
  applicationID: 'VKTN68PL6L'
  apiKey: '5f5fdf04f079fb5d7aa60a0d08c18b53'
  indexName: 'zhuxiuxiang'